title: Gabriel's Guide
description: My guide to things
url: https://gabrielsguide.com

include: 
  - _pages

defaults:
  - scope:
      path: _pages
      type: pages
    values:
      permalink: /:basename

# collections: 
#   content:
#     output: true
#     permalink: /:path

