# frozen_string_literal: true

source "https://rubygems.org"

gem "github-pages", "~> 232", group: :jekyll_plugins

# gem "rails"

gem "webrick", "~> 1.8"

group :jekyll_plugins do
    gem 'jekyll-sitemap'
    gem 'jekyll-seo-tag'
end